<a href="https://colab.research.google.com/github/MOKUAGU/Codes/blob/main/Copy_of_Notebook2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Notebook #2: K Nearest Neighbors and Normalization
**Munachi Okuagu**

**Due: 9/22 before class**

## Load in the data:
You'll notice that there are a lot of columns here. We're going to work with a subset of these columns, not the entire dataset.

In [ ]:
#selecting columns in dataframes
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
#import the data:
#make sure the path on the line below corresponds to the path where you put your dataset.
spotify_data = pd.read_csv('/content/drive/MyDrive/CS167DATASETS/spotify_top_charts.csv')
spotify_data.head()

,uri,artist_names,track_name,peak_rank,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,tempo,time_signature,duration_ms
0,spotify:track:02MWAaffLxlfxAUY7c5dvx,Glass Animals,Heat Waves,1.0,0.761,0.525,11.0,-6.900,1.0,0.0944,0.4400,0.000007,0.0921,80.870,4.0,238805.0
1,spotify:track:5PjdY0CKGZdEuoNab3yDmX,"The Kid LAROI, Justin Bieber",STAY (with Justin Bieber),1.0,0.591,0.764,1.0,-5.484,1.0,0.0483,0.0383,0.000000,0.1030,169.928,4.0,141806.0
2,spotify:track:3IAfUEeaXRX9s9UdKOJrFI,Anitta,Envolver,3.0,0.812,0.736,4.0,-5.421,NaN,0.0833,0.1520,0.002540,0.0914,91.993,4.0,193806.0
3,spotify:track:1HhNoOuqm1a5MXYEgAFl8o,"Imagine Dragons, JID, Arcane, League of Legends",Enemy (with JID) - from the series Arcane Leag...,3.0,0.728,0.783,11.0,-4.424,0.0,0.2660,0.2370,0.000000,0.4340,77.011,4.0,173381.0
4,spotify:track:4fouWK6XVHhzl78KzQ1UjL,GAYLE,abcdefu,1.0,0.695,0.540,4.0,-5.692,1.0,0.0493,0.2990,0.000000,0.3670,121.932,4.0,168602.0

## Exercise #1: 
**Work with the right subset:**

You're not going to work with the whole data set, just the 'artist_names', 'track_name', 'peak_rank', 'duration_ms' and 2-4 additional features of your choice. To start, make this subset of the original data. 

Display the first five rows of your new subset. Also display the number of rows and columns of your subset.

In [ ]:
spotify_music = spotify_data[['artist_names','track_name','peak_rank' ,'duration_ms', 'energy','tempo','acousticness']] #added energy and tempo
spotify_music.head()

,artist_names,track_name,peak_rank,duration_ms,energy,tempo,acousticness
0,Glass Animals,Heat Waves,1.0,238805.0,0.525,80.870,0.4400
1,"The Kid LAROI, Justin Bieber",STAY (with Justin Bieber),1.0,141806.0,0.764,169.928,0.0383
2,Anitta,Envolver,3.0,193806.0,0.736,91.993,0.1520
3,"Imagine Dragons, JID, Arcane, League of Legends",Enemy (with JID) - from the series Arcane Leag...,3.0,173381.0,0.783,77.011,0.2370
4,GAYLE,abcdefu,1.0,168602.0,0.540,121.932,0.2990

## Exercise #2:
**Check for null values**: If you have a null target value ('peak_rank'), you will need to throw that example out. 

Replace each of the null values within your predictors with the average of the column.

*hint: Useful functions here are `isna()`, `any()`, `fillna()`, `notna()` and `dropna()`. If you're not sure what these do, look them up in the [pandas documentation](https://pandas.pydata.org/docs/).*

After you have eliminated null values, use `.isna().any()` to verify that your fields no longer contain any null values (all of the values should be False).

In [ ]:
#spotify_music.isna().any()
pd.options.mode.chained_assignment = None
#print(spotify_music.isna().any())

#print("before: ", spotify_music.shape)
cleaned_spotify = spotify_music.dropna(subset = ['peak_rank'])
#print("after: ", cleaned_spotify.shape)

# drop all null rows
# print("before: ", spotify_music.shape)
# cleaned_spotify = spotify_music.dropna()
# print("after: ", cleaned_spotify.shape)

# print("before: ", spotify_music.shape)
# spotify_music.dropna(inplace=True)
# print("after: ", cleaned_spotify.shape)

print(cleaned_spotify.isna().any())

#print("before: ", cleaned_spotify['peak_rank'].isna().any())
duration_mean = cleaned_spotify['duration_ms'].mean()
cleaned_spotify['duration_ms'].fillna(duration_mean, inplace=True)
print(cleaned_spotify.isna().any())

tempo_mean = cleaned_spotify['tempo'].mean()
cleaned_spotify['tempo'].fillna(tempo_mean, inplace=True)
print(cleaned_spotify.isna().any())

energy_mean = cleaned_spotify['energy'].mean()
cleaned_spotify['energy'].fillna(energy_mean, inplace=True)
print(cleaned_spotify.isna().any())


#print("after: ", cleaned_spotify['peak_rank'].isna().any())
cleaned_spotify.head(5)

artist_names    False
track_name      False
peak_rank       False
duration_ms      True
energy           True
tempo            True
acousticness     True
dtype: bool
artist_names    False
track_name      False
peak_rank       False
duration_ms     False
energy           True
tempo            True
acousticness     True
dtype: bool
artist_names    False
track_name      False
peak_rank       False
duration_ms     False
energy           True
tempo           False
acousticness     True
dtype: bool
artist_names    False
track_name      False
peak_rank       False
duration_ms     False
energy          False
tempo           False
acousticness     True
dtype: bool

,artist_names,track_name,peak_rank,duration_ms,energy,tempo,acousticness
0,Glass Animals,Heat Waves,1.0,238805.0,0.525,80.870,0.4400
1,"The Kid LAROI, Justin Bieber",STAY (with Justin Bieber),1.0,141806.0,0.764,169.928,0.0383
2,Anitta,Envolver,3.0,193806.0,0.736,91.993,0.1520
3,"Imagine Dragons, JID, Arcane, League of Legends",Enemy (with JID) - from the series Arcane Leag...,3.0,173381.0,0.783,77.011,0.2370
4,GAYLE,abcdefu,1.0,168602.0,0.540,121.932,0.2990

In [ ]:
cleaned_spotify

,artist_names,track_name,peak_rank,duration_ms,energy,tempo,acousticness
0,Glass Animals,Heat Waves,1.0,238805.0,0.525,80.870,0.4400
1,"The Kid LAROI, Justin Bieber",STAY (with Justin Bieber),1.0,141806.0,0.764,169.928,0.0383
2,Anitta,Envolver,3.0,193806.0,0.736,91.993,0.1520
3,"Imagine Dragons, JID, Arcane, League of Legends",Enemy (with JID) - from the series Arcane Leag...,3.0,173381.0,0.783,77.011,0.2370
4,GAYLE,abcdefu,1.0,168602.0,0.540,121.932,0.2990
...,...,...,...,...,...,...,...
641,SALES,Pope Is a Rockstar,108.0,187333.0,0.446,90.024,0.8500
642,Morgan Wallen,Don't Think Jesus,96.0,226975.0,0.431,116.979,0.4690
643,"Lil Nas X, YoungBoy Never Broke Again",Late To Da Party (F*CK BET) (feat. YoungBoy Ne...,86.0,180666.0,0.422,149.956,0.0254
644,"Eminem, Snoop Dogg",From The D 2 The LBC (with Snoop Dogg),135.0,215120.0,0.785,82.037,NaN
645,Taylor Swift,Carolina - From The Motion Picture “Where The ...,152.0,264439.0,0.189,115.851,0.9040

## Exercise #3
Write up a k-nearest-neighbors function like the one you made for the iris data set in class. It should be able to make peak rank predictions for new songs. You should also be able to specify what you want to use as k.

You will need to incorporate the predictor features that you have chosen to be a part of your subset in your knn function (but not the artist_names nor track_name).

Pay special attention that I want you to refer to the target variable 'peak_rank' as a value (not a category). Thus, you need to adapt the code to handle a regression.

In [ ]:
import numpy

def knn(song, training_data, k):
  spotify_music = training_data.copy()
  spotify_music['distance_to_new'] = numpy.sqrt(
    (song['energy']-spotify_music['energy'])**2
    +(song['duration_ms']-spotify_music['duration_ms'])**2
    +(song['tempo']-spotify_music['tempo'])**2)
  
  sorted_spotify_music = spotify_music.sort_values(['distance_to_new']) 
  return sorted_spotify_music.iloc[0:k]['peak_rank'].mean()

In [ ]:
my_song = {}
#shivers by ed sheeran  
my_song['energy'] = 0.859
my_song['duration_ms'] = 207853.0	
my_song['tempo'] = 141.02

print('not normalized knn: ', knn (my_song,cleaned_spotify, 1))
#print('not normalized w_knn: ', w_knn (my_song,cleaned_spotify, 3))
#prints out 4.0 knn

not normalized knn:  4.0

## Exercise #4
Demonstrate that your function works by using the values from a song you recognize on the list. Pass in k=1 in to the funtion, and your algorithm should predict the exact peak_rank as your example song.

Make up some new values for a hypothetical new song.  Use your knn function to display a predicted peak_rank for the song. In this case, use a k value that is greater than 1.

I copied the same code from ex.3 and changed the exact values to made up values to predict a 'peak rank' for the new values.

In [ ]:
my_song = {}
#shivers by ed sheeran  
my_song['energy'] = 0.259
my_song['duration_ms'] = 2027853.0	
my_song['tempo'] = 142.02

print('not normalized knn: ', knn (my_song,cleaned_spotify, 4))
#print('not normalized w_knn: ', w_knn (my_song,cleaned_spotify, 3))
#prints out 4.0 knn 
#with random values the function prints out 24.25 as a predicted peak rank based off the values given

not normalized knn:  24.25

## Exercise #5

Make a copy of the data and normalize the training data using Z-score.

*hint: `.copy()` will be useful here.* 

Print out the first 5 lines of the normalized subset.

Predict the peak rank with some input parameters using your k-nearest-neighbors function with both the normalized and non-normalized training data. Compare your results. Use a markup cell to describe and explain the cause of any differences. Detailed responses will receive full credit.

In [ ]:


music_mean = cleaned_spotify['energy'].mean()
music_std = cleaned_spotify['energy'].std()

print(music_mean)
print(music_std)

music_mean = cleaned_spotify['duration_ms'].mean()
music_std = cleaned_spotify['duration_ms'].std()

music_mean = cleaned_spotify['tempo'].mean()
music_std = cleaned_spotify['tempo'].std()

0.6396489731437599
0.16558240888332687

In [ ]:
norm_spotify = {}
# update values in norm_specimin
norm_spotify['energy'] = (0.859 - music_mean)/music_std
norm_spotify['duration_ms'] = (207853.0	 - music_mean)/music_std
norm_spotify['tempo'] = (141.02 - music_mean)/music_std

my_song = {}
#shivers by ed sheeran  
my_song['energy'] = 0.309
my_song['duration_ms'] = 2022153.0	
my_song['tempo'] = 143.50


norm_data_music = {}
norm_data_music = cleaned_spotify.copy()
# update the columns in norm_data 
norm_data_music['energy'] = (cleaned_spotify['energy'] - music_mean)/music_std

norm_spotify['duration_ms'] = (cleaned_spotify['duration_ms'] - music_mean)/music_std
norm_spotify['tempo'] = (cleaned_spotify['tempo'] - music_mean)/music_std

print('normalized knn: ', knn(norm_spotify,norm_data_music, 3))
print('not normalized knn: ', knn (my_song,cleaned_spotify, 3))
#print('normalized w_knn: ', w_knn(norm_spotify,norm_data_music, 3))
#not working ...

normalized knn:  107.0
not normalized knn:  13.0

for the normalized v not normalized data I get different outputs because the numbers for the normalized are on the same scale. in contrast to the data that is not normalized is not on the same scale so the outputs will be different.

Excercise #6 - Do something cool

I took the mean energy, duration, tempo, and acousticness. It is cool to see the mean and std. change from when i was just calculating the three categories.

In [ ]:
music_mean = cleaned_spotify['energy'].mean()
music_std = cleaned_spotify['energy'].std()

music_mean = cleaned_spotify['duration_ms'].mean()
music_std = cleaned_spotify['duration_ms'].std()

music_mean = cleaned_spotify['tempo'].mean()
music_std = cleaned_spotify['tempo'].std()

music_mean = cleaned_spotify['acousticness'].mean()
music_std = cleaned_spotify['acousticness'].std()

print(music_mean)
print(music_std)

0.25720621232227486
0.26441855715371504